// <auto-generated />
using System;
using MafiCo.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MafiCo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260812114048_add_bots_table")]
    partial class add_bots_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mafico")
                .HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MafiCo.Domain.AggregatesModel.ProfileAggregate.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefeatsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("VictoriesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Profiles", "mafico");
                });

            modelBuilder.Entity("MafiCo.Infrastructure.Persistence.Entities.BotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LlmId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LlmId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Bots", "mafico");
                });

            modelBuilder.Entity("MafiCo.Infrastructure.Persistence.Entities.LlmEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LlmData", "mafico");
                });

            modelBuilder.Entity("MafiCo.Infrastructure.Persistence.Entities.BotEntity", b =>
                {
                    b.HasOne("MafiCo.Infrastructure.Persistence.Entities.LlmEntity", "LlmEntity")
                        .WithMany()
                        .HasForeignKey("LlmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafiCo.Domain.AggregatesModel.ProfileAggregate.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LlmEntity");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
